### ISSUE TITLE
missing some files in human_model_files

### ISSUE THREAD

**Issue by marson666** [mks0601/Hand4Whole_RELEASE#1]
Hi, thanks for your great work!

I'm trying to run the demo in your released repo, but i fount that `MANO_SMPLX_vertex_ids.pkl` and `SMPL-X__FLAME_vertex_ids.npy` are not in the human_model_files/smplx folder i downloaded from your read.me, is there any where to download them?

**Comment by mks0601** [comment]
Sorry. I've uploaded it. Thanks!

**Comment by Mamba-ZJP** [comment]
@mks0601 @marson666  Sorry, I still cannot find these two files. Could you tell me where you put it, please?
