### ISSUE TITLE
mano trans parameter is missed

### ISSUE THREAD

**Issue by canghaiyunfan** [mks0601/Hand4Whole_RELEASE#12]
from the json file about FreiHAND dataset, I can't get the parameter about trans.
[the code is here](https://github.com/mks0601/Hand4Whole_RELEASE/blob/2f7a608cb05cf586d1e80c76e507d0802a6c13f0/common/utils/preprocessing.py#L241).

Hand model predict ’cam_trans‘，but not use [here](https://github.com/mks0601/Hand4Whole_RELEASE/blob/2f7a608cb05cf586d1e80c76e507d0802a6c13f0/main/model.py#L87)

Also, bbox_root_freihand_output.json [here](https://github.com/mks0601/Hand4Whole_RELEASE/blob/2f7a608cb05cf586d1e80c76e507d0802a6c13f0/data/FreiHAND/FreiHAND.py#L20) is not offered

**Comment by mks0601** [comment]
For the Frei dataset, ypu should use Pose2Pose branch

cam_trans in hand is used in here: https://github.com/mks0601/Hand4Whole_RELEASE/blob/2f7a608cb05cf586d1e80c76e507d0802a6c13f0/main/model.py#L105

**Comment by mks0601** [comment]
bbox root is available in here: https://drive.google.com/drive/u/0/mobile/folders/1OzwQG2ZutJ4Lzg5psilStsv_MO6-cysA?usp=sharing

Let me add this in reamd later

**Comment by canghaiyunfan** [comment]
Thanks.

FreiHAND  annotations not offer 'trans' para, only have 'pose' and 'shape'

**Comment by mks0601** [comment]
It provdes. Please check the json file.

**Comment by canghaiyunfan** [comment]
Sorry, I used the json file with the same name from other project, which has no 'trans' para.
