### ISSUE TITLE
training about hand model only

### ISSUE THREAD

**Issue by canghaiyunfan** [mks0601/Hand4Whole_RELEASE#14]
I trained a hand model with freihand and interhand2.6M dataset, which the code and config in  Pose2Pose baranch. But the results has a large gap compare to you pre-train model (snapshot_12_hand.pth.tar).

this one is visualize result of your pre-train model
https://user-images.githubusercontent.com/21115878/176083642-369596af-6f95-44e5-97a8-5f2c81191c44.mp4

this one is visualize result of my trained model
https://user-images.githubusercontent.com/21115878/176083797-f18bdefb-9134-421c-95f8-1dfe32cb0a22.mp4

**Comment by mks0601** [comment]
Did you use Frei+IH2.6M? You should use MSCOCO+Frei+IH2.6M.

**Comment by canghaiyunfan** [comment]
Yes, training data use  Frei+IH2.6M, not include MSCOCO. the config is
` trainset_3d = ['FreiHAND', 'InterHand26M']
 trainset_2d = [] `

I will try  MSCOCO+Frei+IH2.6M.
Thanks!
