### ISSUE TITLE
Questions about processing AGORA.

### ISSUE THREAD

**Issue by mls1999725** [mks0601/Hand4Whole_RELEASE#18]
Hi, when I ran agora2coco.py to make the annotation file of AGORA, the following error appeared. I don't know what the problem is, Could you please help me? Thanks a lot !
![image](https://user-images.githubusercontent.com/43207078/177002940-16f7674c-7c31-4e3c-ae28-10bec36cc642.png)

**Comment by buaaswf** [comment]
@mls1999725 hi，I have met the same issue, could you please tell me how to solve this?
