### ISSUE TITLE
Getting image

### ISSUE THREAD

**Issue by nguyenviettuan96** [mks0601/Hand4Whole_RELEASE#2]
Hi, could I ask you a question about getting training data?
Where could I get the data: train2017 and val 2017 like below?
|   |-- MSCOCO  
|   |   |-- images  
|   |   |   |-- train2017  
|   |   |   |-- val2017  
|   |   |-- annotations 
Thank you

**Comment by mks0601** [comment]
https://cocodataset.org/#home

**Comment by nguyenviettuan96** [comment]
thank you
