### ISSUE TITLE
test result looks bad in 3d view

### ISSUE THREAD

**Issue by visonpon** [mks0601/Hand4Whole_RELEASE#21]
Hi @mks0601 ,thanks for sharing the wonderful work . although the rendered result looks good in front view , when rendered from different view(like side), the 3d position for two interaction hand are wrong. so it seems the 3d relationship cannot predicted right.

What's more, I have submit a pr for render the mesh from different view, hope it helps~

**Comment by mks0601** [comment]
Correct. That is my one of ongoing projects.

**Comment by visonpon** [comment]
oh, looking forward your new work,thanks~
