### ISSUE TITLE
cv2.imread() ERROR

### ISSUE THREAD

**Issue by 2choonghyeon** [mks0601/Hand4Whole_RELEASE#24]
First of all, thank you for your awesome work.

While inferencing with my own input.png(not the given one), I got the error like below:

  File "demo.py", line 71, in <module>
    original_img_height, original_img_width = img.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

It worked well with the given input.png, but it doesn't with my own image.
Could I get some advice on this matter from you?

**Comment by mks0601** [comment]
This is the input image path. Please make sure you followed this path.

**Comment by 2choonghyeon** [comment]
[original]
img_path = './input.png'
original_img = cv2.imread(img_path)

[eddited]
img_path = './myinput.png'
original_img = cv2.imread(img_path)

I've just modified the input file name.
Did I do something wrong?

**Comment by mks0601** [comment]
Did you place your test image at `demo/myinput.png`?

**Comment by 2choonghyeon** [comment]
Yes, I did.

**Comment by mks0601** [comment]
And run `python demo.py` in `demo` folder?

**Comment by 2choonghyeon** [comment]
Yes. Only the filename differs.

**Comment by mks0601** [comment]
Please check the file exists correctly by `print(os.path.isfile(img_path))`.

**Comment by 2choonghyeon** [comment]
It prints 'True', but the same error occurs.

**Comment by mks0601** [comment]
can you read the image file with a simple python script without using this code?

**Comment by 2choonghyeon** [comment]
import cv2

im_path = './input.png'
img = cv2.imread(im_path)
print(img.shape)

This simple python script also doesn't work with my image but works well with the given image.

**Comment by mks0601** [comment]
I guess your image is corrupted?

**Comment by 2choonghyeon** [comment]
It was corrupted. Now it is working. Thank you so much!!!!
