### ISSUE TITLE
About the flame model

### ISSUE THREAD

**Issue by linjing7** [mks0601/Hand4Whole_RELEASE#27]
Hi, thank you very much for your excellent work. 

I have a question about the model preparation of the flame. There are several downloading options on the website of flame. Could you please tell me which folder includes  "flame_dynamic_embedding.npy", "flame_static_embedding.pkl", and "FLAME_NEUTRAL.pkl"?

Thank you very much.
![image](https://user-images.githubusercontent.com/70081899/184578004-70b29b6b-0803-4de4-8ed4-67ce42ae163f.png)

**Comment by mks0601** [comment]
I used one of FLAME 2017 and FLAME 2019, but I'm not sure.. Could you try both and see the results?

**Comment by linjing7** [comment]
Okay, thank you very much !

**Comment by linjing7** [comment]
Hi, I'm sorry to trouble you again. 
I download the FLAME 2017 and FLAME 2019 from the provided website. However, the folders contain the following files instead of "FLAME_NEUTRAL.pkl". Can I obtain "FLAME_NEUTRAL.pkl" by renaming "generic_model.pkl"? 
![image](https://user-images.githubusercontent.com/70081899/184795742-cfb6e95a-82ea-4608-9036-d9e29e739e2e.png)

**Comment by mks0601** [comment]
Correct

**Comment by linjing7** [comment]
Okay, thanks very much.
