### ISSUE TITLE
How can I use 3DPW training set for body mesh recovery?

### ISSUE THREAD

**Issue by linjing7** [mks0601/Hand4Whole_RELEASE#30]
Hi, I want to use 3DPW training set during training. However, it lead to "KeyError: 'joint_img'. Could you please tell me how to use it as training set?
Thank you very much!

**Comment by mks0601** [comment]
You can use `smpl_joint_img` instead of `joint_img`.

**Comment by linjing7** [comment]
Hi, in line 154~161 of model.py, both 'joint_img' and 'smpl_joint_img' are needed. 
```
loss['joint_img'] = self.coord_loss(joint_img, smpl.reduce_joint_set(targets['joint_img']), smpl.reduce_joint_set(meta_info['joint_trunc']), meta_info['is_3D'])
                loss['smpl_joint_img'] = self.coord_loss(joint_img, smpl.reduce_joint_set(targets['smpl_joint_img']), smpl.reduce_joint_set(meta_info['smpl_joint_trunc']))
                loss['smpl_pose'] = self.param_loss(smpl_pose, targets['smpl_pose'], meta_info['smpl_pose_valid'])
                loss['smpl_shape'] = self.param_loss(smpl_shape, targets['smpl_shape'], meta_info['smpl_shape_valid'][:,None])
                loss['joint_proj'] = self.coord_loss(joint_proj, targets['joint_img'][:,:,:2], meta_info['joint_trunc'])
                loss['joint_cam'] = self.coord_loss(joint_cam, targets['joint_cam'], meta_info['joint_valid'] * meta_info['is_3D'][:,None,None])
                loss['smpl_joint_cam'] = self.coord_loss(joint_cam, targets['smpl_joint_cam'], meta_info['smpl_joint_valid'])
```
Can I modify the original code to the following code by replacing `joint_img` and `joint_cam` with `smpl_joint_img` and `joint_cam`?
loss['joint_img'] = self.coord_loss(joint_img, smpl.reduce_joint_set(targets['smpl_joint_img']), smpl.reduce_joint_set(meta_info['joint_trunc']), meta_info['is_3D'])
                loss['smpl_joint_img'] = self.coord_loss(joint_img, smpl.reduce_joint_set(targets['smpl_joint_img']), smpl.reduce_joint_set(meta_info['smpl_joint_trunc']))
                loss['smpl_pose'] = self.param_loss(smpl_pose, targets['smpl_pose'], meta_info['smpl_pose_valid'])
                loss['smpl_shape'] = self.param_loss(smpl_shape, targets['smpl_shape'], meta_info['smpl_shape_valid'][:,None])
                loss['joint_proj'] = self.coord_loss(joint_proj, targets['joint_img'][:,:,:2], meta_info['joint_trunc'])
                loss['joint_cam'] = self.coord_loss(joint_cam, targets['smpl_joint_cam'], meta_info['joint_valid'] * meta_info['is_3D'][:,None,None])
                loss['smpl_joint_cam'] = self.coord_loss(joint_cam, targets['smpl_joint_cam'], meta_info['smpl_joint_valid'])

**Comment by mks0601** [comment]
Only for the 3DPW dataset, you can replace it.

**Comment by linjing7** [comment]
Okay, many thanks.
