### ISSUE TITLE
Question about the pseudo labels.

### ISSUE THREAD

**Issue by linjing7** [mks0601/Hand4Whole_RELEASE#32]
Hi, thanks for your excellent work! I have two questions about the pseudo labels:

1. I notice that the number of pseudo labels on MSCOCO datasets you provided is 262461, while SPIN and EFT only provide 28344 and 74834 samples, respectively. Could you please tell me what cause the difference? BTW, will the number of samples greatly affect the performance?

2. Are the format of the `smpl_parms['pose']` in NeuralAnnot the same as that in SPIN/EFT? That is, can I replace the `pose` and `shape` labels in SPIN with the corresponding `pose` and `shape` labels in NeuralAnnot to compare the quality of these pseudo labels?

**Comment by mks0601** [comment]
1. SPIN ignored sampled whose visible keypoints are less than 7 or smth. You can check it by yourself.
2. I guess the format would be the same.

**Comment by linjing7** [comment]
Okay, thank you very much!
