### ISSUE TITLE
model output joint_proj is not correct

### ISSUE THREAD

**Issue by canghaiyunfan** [mks0601/Hand4Whole_RELEASE#33]
I use hand model inference. it can't be display on 2d image correctly.

**Comment by canghaiyunfan** [comment]
@mks0601 How to solve this problem? Can you offer some idea?

**Comment by mks0601** [comment]
Please clearly describe your problem

**Comment by canghaiyunfan** [comment]
Sorry,
the model output [joint_proj](https://github.com/mks0601/Hand4Whole_RELEASE/blob/21ce3c03a4018d6b97324e0df061f026e4d276c0/main/model.py#L137) can't be display on 2d image correctly.

**Comment by canghaiyunfan** [comment]
@mks0601 I have solved this problem. Thanks!

**Comment by skeletonNN** [comment]
Hello, can you share the script for the joint_proj to image?

**Comment by mks0601** [comment]
You can apply the same transformation of joint_img to joint_proj like this
https://github.com/mks0601/Hand4Whole_RELEASE/blob/afcbdf448e5ceeaad6da33776b68c496b4a3edde/main/model.py#L222

**Comment by skeletonNN** [comment]
Thank you for your reply.
Now i want to reprojected the 3d joint_proj to the image, but i don't know what is the image? original image or 192*256 image?
now i get the joint_proj by this:
```python
joint_cam = output.joints[:,smpl_x.joint_idx,:]
x = (joint_cam[:,:,0] + cam_trans[:,None,0]) / (joint_cam[:,:,2] + cam_trans[:,None,2] + 1e-4) * cfg.focal[0] + cfg.princpt[0]
y = (joint_cam[:,:,1] + cam_trans[:,None,1]) / (joint_cam[:,:,2] + cam_trans[:,None,2] + 1e-4) * cfg.focal[1] + cfg.princpt[1]
joint_proj = torch.stack((x,y),2)
```
then i get the image joint for 192*256, is right?
thank you very much.

**Comment by mks0601** [comment]
You can use this joint_proj
https://github.com/mks0601/Hand4Whole_RELEASE/blob/afcbdf448e5ceeaad6da33776b68c496b4a3edde/main/model.py#L146

**Comment by skeletonNN** [comment]
sorry, i want to know the joint_proj is range of x [0-6], y [0-8]？is right?

**Comment by mks0601** [comment]
without this line, they will be in cfg.input_body_shape (512x384 before cropping hand regions)
