### ISSUE TITLE
training hand-only model

### ISSUE THREAD

**Issue by linjing7** [mks0601/Hand4Whole_RELEASE#34]
Hi, thanks for your excellent work. Could you please tell me about the training data configs when training hand-only model? Is the following setting correct: 
```
trainset_3d = ['FreiHAND', 'InterHand26M']
trainset_2d = ['MSCOCO']
```
BTW, are there any other modifications that I need to make when training the hand-only model?

**Comment by mks0601** [comment]
You should use this Pose2Pose branch (https://github.com/mks0601/Hand4Whole_RELEASE/tree/Pose2Pose).
The dataset config is correct

**Comment by linjing7** [comment]
Okay, thank you very much.
