### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'bbox_3d_size'

### ISSUE THREAD

**Issue by linjing7** [mks0601/Hand4Whole_RELEASE#35]
Hi, thank you very much for your excellent work! When I run the full-body version code, an error occurs due to that `config` has no attribute `bbox_3d_size`, can I solve it by adding `bbox_3d_size = body_3d_size`  in config.py?  
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/70081899/193870413-a2fca4d0-1d7f-42c8-96ff-eed4694ed9f4.png">

**Comment by mks0601** [comment]
Sorry. Yes you can use body_3d_size as bbox_3d_size. Let me fix the codes on my side as well.

**Comment by linjing7** [comment]
Okay, thanks for your timely reply.

**Comment by linjing7** [comment]
BTW, I change the output of the backbone into size of `16x16`, instead of `8x8`. And I make the following modifications:
1. In `config.py`:
```
output_hm_shape = (8, 8, 6) -> output_hm_shape = (8, 16, 12) 
output_hand_hm_shape = (8, 8, 8) -> output_hm_shape = (8, 16, 12)
```
2. In line 134-136 of `module.py`:
```
lhand_center = lhand_center / 8 ->  lhand_center = lhand_center / 4
rhand_center = rhand_center / 8 ->  rhand_center = lhand_center / 4
face_center = face_center / 8 ->  face_center = face_center / 4
```
Are there any modifications that I need to make to adapt to the resolution change?

**Comment by mks0601** [comment]
Which backbone did you change in this function?
https://github.com/mks0601/Hand4Whole_RELEASE/blob/2d0b7ddfeec57c2590ea914fccd106f183d7ecb8/main/model.py#L273

There are `backbone`, `hand_backbone`, and `face_backbone`.

**Comment by linjing7** [comment]
I have changed `backbone` and `face_backbone`.

**Comment by mks0601** [comment]
You should change only ₩output_hm_shape = (8, 16, 12)₩ in `config.py`. 
Did you change the number of deconv layers [here](https://github.com/mks0601/Hand4Whole_RELEASE/blob/2d0b7ddfeec57c2590ea914fccd106f183d7ecb8/common/nets/module.py#L110)? If not, you do not have to change /8  -> /4

**Comment by linjing7** [comment]
Sorry, I have changed backbone and hand_backbone. And I have changed the number of deconv layers into:
`self.deconv = make_deconv_layers([768 + self.joint_num * cfg.output_hm_shape[0], 256, 256])`

**Comment by mks0601** [comment]
Then, your previous question (https://github.com/mks0601/Hand4Whole_RELEASE/issues/35#issuecomment-1267281315) is correct except for output_hand_hm_shape = (8, 8, 8) -> output_hm_shape = (8, 16, 12). You should make it to (8, 16, 16), not (8, 16, 12).

**Comment by linjing7** [comment]
Okay, thank you very much!
