### ISSUE TITLE
Any body knows how to place the directory?

### ISSUE THREAD

**Issue by jihg88** [mks0601/Hand4Whole_RELEASE#37]
![image](https://user-images.githubusercontent.com/50345299/194551579-0c087174-d005-46e7-a6f9-cf49e772c5a0.png)
I followed the picture like this ,but i don't know the meaning of the sentence below.
![image](https://user-images.githubusercontent.com/50345299/194551890-4eac834b-98a8-4265-9ed8-e717452fef45.png)
what should i do with the file human_model_files.

And i got problems with load the model now.
![image](https://user-images.githubusercontent.com/50345299/194552377-8aa1b4b5-c493-45c8-bc65-2bf1ccca5d90.png)

**Comment by mks0601** [comment]
Did you this instruction?
human_model_files contains smpl, smplx, mano, and flame 3D model files. Download the files from [[smpl]](https://smpl.is.tue.mpg.de/) [[smplx]](https://smpl-x.is.tue.mpg.de/) [[SMPLX_to_J14.pkl]https://github.com/vchoutas/expose#preparing-the-data] [[mano]](https://mano.is.tue.mpg.de/) [[flame]](https://flame.is.tue.mpg.de/).

**Comment by jihg88** [comment]
i have downloaded most of them ,but the "FLAME_NEUTRAL.pkl" i don't know where to get it.
and i think this is not the main reason i got the error

**Comment by mks0601** [comment]
Sorry the path in the README was slightly wrong. I updated.

**Comment by jihg88** [comment]
Thanks for your reply ,i add some pkl files  now, and it seems fixed,but there is a new error.
![image](https://user-images.githubusercontent.com/50345299/194571957-d94eced4-58cd-421b-8608-7ed746d912ae.png)
Do you know how to handle this?
 And  i need the file:FLAME_NEUTRAL.pkl,i want to know which version should i download in Flame page

**Comment by mks0601** [comment]
Which versions are available?

**Comment by jihg88** [comment]
i can download the Flame-2020、2019、2017 version,but i found the name is not the same as your instruction.
![image](https://user-images.githubusercontent.com/50345299/194575806-3ee5a9f7-cf0c-4e9c-9a5c-edf01cd712e0.png)
Should i rename them?

**Comment by mks0601** [comment]
Yes you should rename them. Sorry I can't remember clearly which version I used, but maybe 2017 or 2019 would be safe

**Comment by jihg88** [comment]
it worked, thank you very much

**Comment by sylyt62** [comment]
@jihg88 where did you get flame_dynamic_embedding and flame_static_embedding files? I couldn't find this two..:(

**Comment by jihg88** [comment]
@sylyt62 
This is the link I used
https://github.com/soubhiksanyal/RingNet/tree/master/flame_model

**Comment by sylyt62** [comment]
> @sylyt62 This is the link I used https://github.com/soubhiksanyal/RingNet/tree/master/flame_model

Cool! Thx a lot!
