### ISSUE TITLE
The performance of Hand4Whole in first stage

### ISSUE THREAD

**Issue by linjing7** [mks0601/Hand4Whole_RELEASE#38]
Hi, in Hand4Whole branch, multi-stages training is needed and could you please tell me about the performance `after the first stage,` i.e., `pre-train Hand4Whole`. My performance is as follows and I think there may be something wrong.
<img width="299" alt="image" src="https://user-images.githubusercontent.com/70081899/194995070-0757145b-552f-4ba3-b6db-fb5187a474f4.png">

**Comment by mks0601** [comment]
On which dataset? Why do you think something's wrong?

**Comment by linjing7** [comment]
Hi, on EHF dataset. Because this result is about 2mm worser than the paper. I think pretraining on hand dataset would only significantly improve the performance on the hand part?

**Comment by mks0601** [comment]
I guess somewhere around 
PA MPVPE all / hands / face: 50.24 / 11.69 / 5.77

**Comment by linjing7** [comment]
Okay, thank you very much.

**Comment by olga-zats** [comment]
@linjing7 Hi! Were you able to get around this issue?

**Comment by linjing7** [comment]
@olga-zats Not yet.

**Comment by RockyXu66** [comment]
> I guess somewhere around PA MPVPE all / hands / face: 50.24 / 11.69 / 5.77

Hi mks0601! Thanks for your excellent work. 

I want to reproduce your hand4whole training result. I follow your README instruction by using the pretrained `body_pose_resnet_50_256x192.pth.tar` model in first stage and rename it to `snapshot_0.pth.tar`. But I got the similar result with @linjing7 which is a little far from your provided scores. This is the test score of first stage on my own `snapshot_6.pth.tar` model.
![image](https://user-images.githubusercontent.com/18605943/199644904-e3b0b8f9-3332-424d-8b54-1ded50abec7c.png)

btw, my training command is `python train.py --gpu 1,2,3,4 --lr 1e-4 --continue`.  The configuration in 'Config.py' keeps the same in your git. 
``` python
## dataset (use names in the `data` folder)
trainset_3d = ['Human36M']
trainset_2d = ['MSCOCO', 'MPII'] 
testset = 'EHF'

## model setting
resnet_type = 50
hand_resnet_type = 50
face_resnet_type = 18

## input, output
input_img_shape = (512, 384) 
input_body_shape = (256, 192)
output_hm_shape = (8, 8, 6)
input_hand_shape = (256, 256)
output_hand_hm_shape = (8, 8, 8)
input_face_shape = (192, 192)
focal = (5000, 5000) # virtual focal lengths
princpt = (input_body_shape[1]/2, input_body_shape[0]/2) # virtual principal point position
body_3d_size = 2
hand_3d_size = 0.3
face_3d_size = 0.3
camera_3d_size = 2.5

## training config
lr_dec_factor = 10
lr_dec_epoch = [4,6] #[40, 60] #[4,6]
end_epoch = 7 #70 #7
train_batch_size = 24

## testing config
test_batch_size = 64
```

**Comment by linjing7** [comment]
Hi, @mks0601, all of us can not achieve the performance you provided after the first stage. Is it caused by the PyTorch version or anything others?  I use python3.7 and torch1.7.1.

**Comment by mks0601** [comment]
You might want to try full training (three stage training) as the errors of the first stage (PA MPVPE all / hands / face: 50.24 / 11.69 / 5.77) might be wrong.

**Comment by linjing7** [comment]
Okay, thank you very much.

**Comment by Britton-Li** [comment]
@RockyXu66 , Could you please send me the Human3.6M data
