### ISSUE TITLE
Question about bbox_3d_size and camera_3d_size.

### ISSUE THREAD

**Issue by canghaiyunfan** [mks0601/Hand4Whole_RELEASE#39]
Why add ''bbox_3d_size' and 'camera_3d_size' in config file? How to set their value？

**Comment by mks0601** [comment]
bbox_3d_size: target object size (for hands, about 0.2 meter).
camera_3d_size: a little bit larger than bbox_3d_size, used to calculate 3D global translation

**Comment by canghaiyunfan** [comment]
Got it, Thank you!
