### ISSUE TITLE
The difference of body_pose between 'MSCOCO_train_SMPL_NeuralAnnot.json' and 'MSCOCO_train_SMPLX_all_NeuralAnnot.json' 

### ISSUE THREAD

**Issue by linjing7** [mks0601/Hand4Whole_RELEASE#45]
Hi, thanks for your excellent work. I notice that the `body_pose` param in `MSCOCO_train_SMPLX_all_NeuralAnnot.json` is quite different from that in `MSCOCO_train_SMPL_NeuralAnnot.` Here is my code and could you please tell me what cause the difference?
<img width="888" alt="image" src="https://user-images.githubusercontent.com/70081899/199010336-4ac1a69d-6378-45dd-a003-b3dead02633b.png">
<img width="1867" alt="image" src="https://user-images.githubusercontent.com/70081899/199010389-ab74244e-f6fc-4486-a0fb-377019fe3ba1.png">

**Comment by mks0601** [comment]
Of course they are different. 
MSCOCO_train_SMPLX_all_NeuralAnnot.json -> SMPLX 
MSCOCO_train_SMPL_NeuralAnnot.json -> SMPL

**Comment by linjing7** [comment]
As mentioned in `NeuralAnnot` and the code of Hand4Whole, the `SMPLX` param is integrated by the `SMPL`, `MANO`, and `FLAME` params. Therefore, I think the `body part` of SMPLX param should be the same as SMPX param? If not, could you please show me about the intergration code?
`pose = torch.cat((root_pose, body_pose, lhand_pose, rhand_pose, jaw_pose), 1)`
<img width="529" alt="image" src="https://user-images.githubusercontent.com/70081899/199015293-2b211ae3-0bce-4330-a5d6-5fc68db81cfd.png">

**Comment by linjing7** [comment]
Okay, got it, thank you very much.  Could you please share the code to transfer the MANO parameter into `hand_pose` of SMPLX?

**Comment by mks0601** [comment]
Are you talking about neuralannot? Hand4Whole does not require it

**Comment by linjing7** [comment]
Yes, because I notice that the param of hand_pose is also different in MANO and SMPLX, I know that it's caused by multiplying the inverse 3D elbow global rotation. But I'm afraid that I can not correctly implement it.

**Comment by linjing7** [comment]
Hi, I'm sorry that the param of hand_pose of MANO and SMPLX are the same except for the root_pose. Thank you very much for your patient reply.
