### ISSUE TITLE
joint_img processing.

### ISSUE THREAD

**Issue by chenmingTHU** [mks0601/Hand4Whole_RELEASE#46]
Hi mks0601,
I find that the function process_db_coord in preprocessing.py discretizes the root-relative depth channel of joint_img:
![image](https://user-images.githubusercontent.com/22796506/200262245-2310159c-ff6f-4781-b70c-f32847906037.png)
while the discretization is also conducted in each dataset (e.g., MPI_INF_3DHP):
![image](https://user-images.githubusercontent.com/22796506/200262526-157b9c15-1096-45c5-83cc-6e8fed4bfcfb.png)
Is it necessary to conduct the discretization process twice? thx~

**Comment by mks0601** [comment]
Why do you think there are two discretizations? There is only one

**Comment by chenmingTHU** [comment]
> Why do you think there are two discretizations? There is only one

In MPI_INF_3DHP, the joint_img[:, 2] is discretized, then the joint_img is sent to process_db_coord function. 
![image](https://user-images.githubusercontent.com/22796506/200268506-f8d21ef7-05c5-4a6f-8734-fdaf29f08e28.png)
In process_db_coord function (line 186), the joint_img[:, 2] is discretized again?
![image](https://user-images.githubusercontent.com/22796506/200268589-2ece48b4-730f-4fcd-b33f-31c01721116c.png)

**Comment by mks0601** [comment]
Oh.. that is a bug.. Thanks for letting me know and let me update codes now

**Comment by mks0601** [comment]
I've updated codes. You can just delete that line in preprocessing.py

**Comment by chenmingTHU** [comment]
> I've updated codes. You can just delete that line in preprocessing.py

Thanks for replying :)
