### ISSUE TITLE
Question about SMPLX hand only prediction

### ISSUE THREAD

**Issue by buaacyw** [mks0601/Hand4Whole_RELEASE#51]
Hi! Thanks for your work.
I want to ask if it is possible to perform hand-only prediction for SMPLX models.
I have seen the hand-only prediction for MANO models.
I wonder if it is possible to translate the MANO prediction to SMPLX prediction (only the hand part of SMPLX).
Thanks!

**Comment by mks0601** [comment]
What do you mean by only the hand part of SMPLX? As hands are connected with body in SMPLX, kinematic chain of hands is connected to the body. That means, ancestor joints (body joints) should be supervised as well for hand prediction. For example, given two hand/finger positions, you can randomly place other body parts such as elbow or lower body parts

**Comment by buaacyw** [comment]
Yes. That is exactly what I want.
I don't care about other body parts of the SMPLX. I only need the hand parts (just one hand) to fit the image.
I found in SMPLX repo that MANO vertices can be mapped to the SMPLX vertices.
But I need the whole SMPLX model. So Is this possible?

**Comment by mks0601** [comment]
You can make rotations of other parts to zero and make 3D wrist local rotation to the 3D global hand rotation.

**Comment by buaacyw** [comment]
> You can make rotations of other parts to zero and make 3D wrist local rotation to the 3D global hand rotation.

Thanks! I think this is feasible.
