### ISSUE TITLE
Weird result for left hand only prediction

### ISSUE THREAD

**Issue by buaacyw** [mks0601/Hand4Whole_RELEASE#52]
Hi! Thanks for your great work.
When I was using the hand-only prediction demo, I found the left-hand result weird like below.
![00000_overlay_left](https://user-images.githubusercontent.com/52091468/204286236-0d818ffc-d83a-4c19-9d23-1fc2c53bc662.jpg)

Then I removed [this line](https://github.com/mks0601/Hand4Whole_RELEASE/blob/491da3048506d28ab274989c4a6c04fa8b1eae83/demo/hand/demo_hand.py#L83) and got another weird result like below.
![00000_overlay_left](https://user-images.githubusercontent.com/52091468/204285922-2a698ca6-d047-4b83-a383-164fc6ec4ccc.jpg)
After removing that line, for the left-hand data like this, it works fine.
![00026_overlay_left](https://user-images.githubusercontent.com/52091468/204286029-fdd85216-f5eb-4d3c-adbf-4bc5bb948758.jpg)

And all the right-hand result is nice.
So what's the problem? I'm really confused.

**Comment by mks0601** [comment]
Hi, I forgot to add this line: https://github.com/mks0601/Hand4Whole_RELEASE/blob/aeb6ab5020dc77e4e5c8e8b5fc33cf072f5372e5/demo/hand/demo_hand.py#L83
I've just added. Could you try again?

**Comment by buaacyw** [comment]
Thanks! It works nicely!
