### ISSUE TITLE
Evaluation for InterHand2.6M

### ISSUE THREAD

**Issue by redorangeyellowy** [mks0601/Hand4Whole_RELEASE#55]
Hello. I'm trying to learn about InterHand2.6M and conduct a test about it, but the test code is empty. Can I ask you to share the code for this?

**Comment by mks0601** [comment]
Are you going to use InterHand2.6M with hand-only Pose2Pose? If you are just interested in 3D interacting hand recovery, you might want to visit this site: https://github.com/facebookresearch/InterHand2.6M

**Comment by redorangeyellowy** [comment]
Yes. I want to use hand-only Pose2Pose, so I trained it with InterHand2.6M.

But I cannot find the evaluation code in here: https://github.com/mks0601/Hand4Whole_RELEASE/blob/Pose2Pose/data/InterHand26M/InterHand26M.py

How can I test my trained model?

**Comment by mks0601** [comment]
I've added evaluation code. I didn't tested the code so there can be runtime error, so please let me know if you have

**Comment by redorangeyellowy** [comment]
Okay. I'll check this code ASAP. Thank you for your reply.
