### ISSUE TITLE
Some question about the initial pose of body and hand

### ISSUE THREAD

**Issue by henrycjh** [mks0601/Hand4Whole_RELEASE#56]
Thanks for your great work! 
I have learned that the SMPL-X use the pose parameters to get the final pose from the initial pose (T-Pose), and the pose parameters for each joints is the axis-angle format rotation relative to its parent's rotation. However, I have no detail information about the actual initial coordinate of each joints, including body and hands (especially for the hands). I have tried to search in the original paper, but still got nothing. 
Here is an example that I would like to know about the initial coordinates.
![joint-coordinates](https://user-images.githubusercontent.com/73419275/208063703-49055d7f-a62b-48d3-8782-1b1d43d5e2db.png)

Is there any documentation about it? 
Thanks for your attention!

**Comment by mks0601** [comment]
Could you clarify what you want is xyz axis of each joint's rotation? Or you want is just a joint set?

**Comment by henrycjh** [comment]
> Could you clarify what you want is xyz axis of each joint's rotation? Or you want is just a joint set?

Thanks for your reply. I want the initial xyz axis of each joints.

**Comment by mks0601** [comment]
Unfortunately, you should figure out them manually as far as I know. You can change rotation of each axis of each joint and visualize meshes to check axis directions..

**Comment by mks0601** [comment]
Maybe you could leave an issue to official SMPL-X git repo
