### ISSUE TITLE
[Hand4Whole]A problem on Agora

### ISSUE THREAD

**Issue by cyk990422** [mks0601/Hand4Whole_RELEASE#58]
This is an excellent job. I had a small problem when I reproduced it on Agora. The global rotation parameter in SMPL parameters given by Agora is in the world coordinate system. How did you convert it to the camera coordinate system?

**Comment by mks0601** [comment]
Hi, yes you're right.
AGORA dataset provides joint/mesh coordinates in camera-centered coordinate system and smplx parameters in world coordinate system.
As you can see [here](https://github.com/mks0601/Hand4Whole_RELEASE/blob/0e7871d41433dfbb27a58ecb1a9dbc3a55de8f2d/data/AGORA/AGORA.py#L338), I do not use global rotation of smplx for the supervision.
