### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by henrycjh** [mks0601/Hand4Whole_RELEASE#60]
I can't find the file MANO_SMPLX_vertex_ids.pkl and SMPL-X__FLAME_vertex_ids.npy you listed in README. Could you please provide some suggestions on how to download them?

**Comment by henrycjh** [comment]
I have found it in https://smpl-x.is.tue.mpg.de/download.php

**Comment by sdgumdam** [comment]
to be more specific it is the MANO and FLAME vertex indices
<img width="409" alt="image" src="https://github.com/mks0601/Hand4Whole_RELEASE/assets/8412026/7e1f16ce-c36d-40de-97f0-231feddd0b85">
