### ISSUE TITLE
About hand pose

### ISSUE THREAD

**Issue by henrycjh** [mks0601/Hand4Whole_RELEASE#62]
I got the pose of hands from the output of the demo code. When I apply the pose to an avatar, its hands have weird pose. I guess it is related to the parameter "flat_hand_mean" of the SMPLX model. So I am wondering if the Hand4Whole model is trained with flat_hand_mean=False? If I would like a initial "flat hand", should I train the model from scratch?

**Comment by mks0601** [comment]
Yes it is traiend with flat_hand_mean=False, and you can check here to get that
https://github.com/vchoutas/smplx/blob/main/smplx/body_models.py

**Comment by henrycjh** [comment]
Thanks for your reply. I would check it now.

**Comment by mks0601** [comment]
you can simply add subtract the mean pose from the current estimated hand pose if you want some hand pose with flat_hand_mean=True

**Comment by sarsigmadelta** [comment]
> mean

thank you so much for reply, you meaning finetuing model is not actually necessary ?   we just need to subtract the mean pose ,then we can get the right pose ?

**Comment by mks0601** [comment]
Yeap. you can see what they do internally
https://github.com/vchoutas/smplx/blob/1265df7ba545e8b00f72e7c557c766e15c71632f/smplx/body_models.py#L630
https://github.com/vchoutas/smplx/blob/1265df7ba545e8b00f72e7c557c766e15c71632f/smplx/body_models.py#L737C15-L737C15

**Comment by sarsigmadelta** [comment]
> Yeap. you can see what they do internally https://github.com/vchoutas/smplx/blob/1265df7ba545e8b00f72e7c557c766e15c71632f/smplx/body_models.py#L630 https://github.com/vchoutas/smplx/blob/1265df7ba545e8b00f72e7c557c766e15c71632f/smplx/body_models.py#L737C15-L737C15

Appreciate it!
