### ISSUE TITLE
Hand parts result on InterHand26M

### ISSUE THREAD

**Issue by aragakiyui611** [mks0601/Hand4Whole_RELEASE#72]
I tested the hand part of Hand4Whole and the result is `MPJPE: 63.86 mm`, is it reasonable? Did you test the model in terms of  MPJPE on InterHand26M and may I know your result? Thank you!

**Comment by mks0601** [comment]
For the hand-only images, you should use Pose2Pose (https://github.com/mks0601/Hand4Whole_RELEASE/tree/Pose2Pose)

**Comment by mks0601** [comment]
mpjpe 63 is not a making sense number. it's too big. I guess there should be some bugs? How did you evaluate on ih2.6m dataset?

**Comment by aragakiyui611** [comment]
[InterHand26M.py.txt](https://github.com/mks0601/Hand4Whole_RELEASE/files/11469859/InterHand26M.py.txt)
I using the same code as that in the repository, my trained weights perform normally on other datasets like FreiHAND, COCO

**Comment by mks0601** [comment]
joint_gt includes both right/left hands, while the output only includes the right hand.

**Comment by aragakiyui611** [comment]
Thank you! I flip back the left hands and MPJPE now is 18.21mm

**Comment by mks0601** [comment]
Please note that for the fair comparison to previous works, you should train the network again after removing this view sampling.
https://github.com/mks0601/Hand4Whole_RELEASE/blob/39fd3727ac1729c0ce59890986e41abbce0f9955/data/InterHand26M/InterHand26M.py#L56

**Comment by aragakiyui611** [comment]
Thank you!

**Comment by mks0601** [comment]
Try this at below

https://github.com/mks0601/I2L-MeshNet_RELEASE#data

**Comment by aragakiyui611** [comment]
> Try this at below
> 
> https://github.com/mks0601/I2L-MeshNet_RELEASE#data

It seems that this is the one I use, I cannot download it either

**Comment by aragakiyui611** [comment]
Thank you every much!
