### ISSUE TITLE
About process_db_coord

### ISSUE THREAD

**Issue by 124518** [mks0601/Hand4Whole_RELEASE#75]
hellow,your work is really good and I have a question about pre-process data.https://github.com/mks0601/Hand4Whole_RELEASE/blob/afcbdf448e5ceeaad6da33776b68c496b4a3edde/data/Human36M/Human36M.py#L149
before this code,you have got the joint_img, joint_cam from the josn,and this line process the  joint_img and joint_cam again.why did this and will this action would broken the Original data.

**Comment by mks0601** [comment]
You can read this function why I do that
https://github.com/mks0601/Hand4Whole_RELEASE/blob/afcbdf448e5ceeaad6da33776b68c496b4a3edde/common/utils/preprocessing.py#L163

**Comment by 124518** [comment]
Thank you very much for your answer！And I have another question,in your work, you got tz through the below function, but other ways  got tz through 2f/(res *s),which is weak perspective, I want to know the difference between them, Thank you very much if you can answer me. 
https://github.com/mks0601/Hand4Whole_RELEASE/blob/afcbdf448e5ceeaad6da33776b68c496b4a3edde/main/model.py#L36

**Comment by mks0601** [comment]
what do res and s mean in 2f/(res * s)?

**Comment by 124518** [comment]
f = 5000 ,  denotes predefined  focal length,  s is the scale parameter, in your codes, I think it is cam_param[:,2],but I am not sure.res denotes the  resolution of the resized  crop image.

**Comment by mks0601** [comment]
I do not think there is a significant difference.

**Comment by 124518** [comment]
Thank you for your reply, but I can't understant k_value, why calculat  k_valueb in this formula.
https://github.com/mks0601/Hand4Whole_RELEASE/blob/afcbdf448e5ceeaad6da33776b68c496b4a3edde/main/model.py#L40

**Comment by 124518** [comment]
And I note that You also use output_hm_shape when normalizing,What role does output_hm_shape play here?Looking forward to your answer.

**Comment by mks0601** [comment]
Please Sec 1 of suppl of https://arxiv.org/pdf/1907.11346.pdf for the k value
As you said, it is just for normalizing coordinates

**Comment by 124518** [comment]
OK.Thank you very much for your reply!

**Comment by 124518** [comment]
Hellow, I read your paper carefully and have two questions I would like to ask you.In the below formula, what are the values of f and px, and do you assume that f is 5000?Looking forward to your reply.
![image](https://github.com/mks0601/Hand4Whole_RELEASE/assets/100846916/c80da498-40c1-4714-a68d-d85e0e0e795f)

**Comment by mks0601** [comment]
Hi, as in-the-wild images do not provide focal lengths, I assume focal length as 5000, following previous works. Actually, alpha_x is what we need, which is a focal length in pixel unit, and that is assumes to be 5000.

**Comment by 124518** [comment]
OK, I got it.Thank you very much!

**Comment by 124518** [comment]
Hello,in the paper, the actual area of the human body is preset as 2*2(m), but the preset value in your code is 2.5, why is this? Is this related to the detected body frame?Is gamma the correction factor in the paper?Thank you very much for your reply! 
![image](https://github.com/mks0601/Hand4Whole_RELEASE/assets/100846916/b232504b-76b0-473a-b22f-e8b21dda38b3)

**Comment by mks0601** [comment]
It doesn't matter. The k_value would be proportionally increased.

**Comment by 124518** [comment]
OK.Thank you very much!
