### ISSUE TITLE
hand only result

### ISSUE THREAD

**Issue by Dong09** [mks0601/Hand4Whole_RELEASE#80]
Hello, after running the hand_only script, I got a less than ideal result,both the angle and size of the mesh do not match, I would like to ask why this is the case, the picture is below:
![微信截图_20231025153348](https://github.com/mks0601/Hand4Whole_RELEASE/assets/45942487/a4881b24-bedb-4ae2-af8b-6fb5586b4e04)
![微信截图_20231025153407](https://github.com/mks0601/Hand4Whole_RELEASE/assets/45942487/78e58638-75fe-4700-a2e7-2b3fe831db58)

**Comment by mks0601** [comment]
Hi, there was a bug in the demo code. The image should be read with load_img function, which basically change BGR -> RGB, but the old code used BGR as an input of the network. I fixed it. Could you try agin?

**Comment by Dong09** [comment]
> Hi, there was a bug in the demo code. The image should be read with load_img function, which basically change BGR -> RGB, but the old code used BGR as an input of the network. I fixed it. Could you try agin?

Yes, the above result is the image loaded with the load_img function, will this be the cause of the bad result

**Comment by mks0601** [comment]
Did you use this code (https://github.com/mks0601/Hand4Whole_RELEASE/blob/Pose2Pose/demo/hand/demo_hand.py) for the result? If so, the code that you used was not using load_img function, so could you try again with the updated one?

**Comment by Dong09** [comment]
thks,i have used mediapipe that get the hand bbox to solved the problem.
And I would like to know how to solve the problem of unpredictable afterimage caused by high-speed hand movement

**Comment by mks0601** [comment]
that is still not been explored much. we're pushing for that direction and one of our previous work is here https://arxiv.org/abs/2303.15417

**Comment by Dong09** [comment]
> that is still not been explored much. we're pushing for that direction and one of our previous work is here https://arxiv.org/abs/2303.15417

thks a lot. And if I add a few of the following training sets, can I improve the accuracy of my hands with blur motion?
![image](https://github.com/mks0601/Hand4Whole_RELEASE/assets/45942487/36f8fcc1-97d1-4ce2-8199-6ff66c945179)

**Comment by mks0601** [comment]
So far, BlurHand dataset is the only one that provides 3D GT from blurry hand images.

**Comment by Dong09** [comment]
thks for your reply！it is helpful.

**Comment by Dong09** [comment]
When I use the same render mesh function as Hand4Whole to render BlurHand's mesh, I get the following situation, the image and code are as follows.

![微信截图_20231108105309](https://github.com/mks0601/Hand4Whole_RELEASE/assets/45942487/d1c0b39d-5d24-456f-a138-5dd73bd87a6e)
```
def render_mesh(img, mesh, face, cam_param):
    # mesh
    mesh = trimesh.Trimesh(mesh, face)
    rot = trimesh.transformations.rotation_matrix(
	np.radians(180), [1, 0, 0])
    mesh.apply_transform(rot)
    material = pyrender.MetallicRoughnessMaterial(metallicFactor=0.0, alphaMode='OPAQUE', baseColorFactor=(1.0, 1.0, 0.9, 1.0))
    mesh = pyrender.Mesh.from_trimesh(mesh, material=material, smooth=False)
    scene = pyrender.Scene(ambient_light=(0.3, 0.3, 0.3))
    scene.add(mesh, 'mesh')
    focal, princpt = cam_param['focal'], cam_param['princpt']
    camera = pyrender.IntrinsicsCamera(fx=focal[0], fy=focal[1], cx=princpt[0], cy=princpt[1])
    scene.add(camera)
    # renderer
    renderer = pyrender.OffscreenRenderer(viewport_width=img.shape[1], viewport_height=img.shape[0], point_size=1.0)
    # light
    light = pyrender.DirectionalLight(color=[1.0, 1.0, 1.0], intensity=0.8)
    light_pose = np.eye(4)
    light_pose[:3, 3] = np.array([0, -1, 1])
    scene.add(light, pose=light_pose)
    light_pose[:3, 3] = np.array([0, 1, 1])
    scene.add(light, pose=light_pose)
    light_pose[:3, 3] = np.array([1, 1, 2])
    scene.add(light, pose=light_pose)
    # render
    rgb, depth = renderer.render(scene, flags=pyrender.RenderFlags.RGBA)
    rgb = rgb[:,:,:3].astype(np.float32)
    valid_mask = (depth > 0)[:,:,None]
    # save to image
    img = rgb * valid_mask + img * (1-valid_mask)
    return img
self.opt_params['focal'] = [5000,5000]
self.opt_params['input_img_shape'] = [256,256]
focal = [self.opt_params['focal'][0] / self.opt_params['input_img_shape'][1] * out['bbox'][2], self.opt_params['focal'][1] / self.opt_params['input_img_shape'][0] * out['bbox'][3]]
princpt = [self.opt_params['princpt'][0] / self.opt_params['input_img_shape'][1] * out['bbox'][2] + out['bbox'][0], self.opt_params['princpt'][1] / self.opt_params['input_img_shape'][0] * out['bbox'][3] + out['bbox'][1]]

rendered_img = render_mesh(blur_img, mesh_out*np.array([1,-1,-1]), mano.face['right'], {'focal': focal, 'princpt': princpt})
```
