### ISSUE TITLE
Datasets about  the provided full-body model

### ISSUE THREAD

**Issue by blahole** [mks0601/Hand4Whole_RELEASE#88]
The training of the provided full-body model, did it involve these three hand datasets：FreiHAND+InterHand2.6M+MSCOCO?
![Snipaste_20240329_170324](https://github.com/mks0601/Hand4Whole_RELEASE/assets/30015000/5434cb78-5ed2-4e24-b31d-dca4558f0337)
![Snipaste_20240329_170545](https://github.com/mks0601/Hand4Whole_RELEASE/assets/30015000/66c6c57a-8db9-4284-af50-af0932b7cd9c)

**Comment by mks0601** [comment]
Yeap the first one is already pre-trained on the three hand-only datasets.

**Comment by blahole** [comment]
Alright, thanks！
